application: visirportal
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /visir_html5
  static_dir: visir_html5
- url: .*
  script: main.app
